### PR TITLE
Gcc-patch-simplified

### PR DESCRIPTION
**Pull request by Swat-SomeBug**
Modified gcc patch to disable `__COUNTER__` expression by default.
Allow conditional enable of the expression using `BENCHMARK_FORCE_COUNTER_INC_TEST`

### CODE REVIEW

**Comment by helmesjo** [comment]
I'm having trouble consuming this package (any branch), but then again I'm pretty new to build2. I've setup the repository (github url), manifest `depends` & can import the library, but it fails to find the `<benchmark/benchmark.h>` (when building this lib). AFAIK, it doesn't appear to fetch the submodule (the actual google benchmark repo). I'm I missing something (most likely, but can't find anything in the docs), or is the export options perhaps not setup correctly?

**Comment by helmesjo** [comment]
Same for both GCC & Clang. If I manually specify include path manually when building my project (which depends on `google-benchmark`) it **works**:
```
bdep update @gcc config.cc.poptions+=-I/home/user/proj-gcc/.bpkg/repos/93e5a2205f0d/include
```
**does not work:**
```
bdep update @gcc
[...]
trace: cxx::compile_rule::enter_header: non-existent header 'benchmark/benchmark.h'
```

I think the issue is that it's exported for `cxx` (thus not available when building google benchmark in `C`). So I guess [this](https://github.com/build2-packaging/google-benchmark/blob/7c0f113b19ec8cb5c0ba40698330a4cc5837816b/src/buildfile#L32) should be changed to `cc` instead of `cxx`..? (or maybe not, changing my command line above to `config.cxx.poptions` still works. shooting in the dark here)

**Comment by Swat-SomeBug** [comment]
@helmesjo, I'm unable to reproduce the issue.

Building automatically:
I created a simple test and declared the dependency in `manifest`
`depends: google-benchmark`
and added the repo in `repositories.manifest`
```
:
role: prerequisite
type: git
location: https://github.com/build2-packaging/google-benchmark.git#gcc-patch-simplified
```
Build went through without issues.

Building using `bpkg` also seems to work:
```
bpkg create -d pkg-test
cd pkg-test
bpkg add https://github.com/build2-packaging/google-benchmark.git\#gcc-patch-simplified
bpkg fetch && bpkg build google-benchmark
bpkg test google-benchmark
```

>  think the issue is that it's exported for cxx (thus not available when building google benchmark in C). So I guess this should be changed to cc instead of cxx..? (or maybe not, changing my command line above to config.cxx.poptions still works. shooting in the dark here)

I'm not really sure what this means. `google-benchmark` itself requires `c++11` for building, though `c++03` code can be tested. The translation unit which declares the test using `BENCHMARK(<function-name>)` should be compiled as a `c++` source. So, one would be loading `cxx`. So as I understand, even when one requires to benchmark some `c` code, `cxx` module should always to be loaded.

Is it possible to share your code or part of it that links the library? Maybe a github repo?

**Comment by helmesjo** [comment]
Okay, so the issue is simply that the `/include/benchmark/benchmark.h` subdirectory & header is missing in the configuration when the git repository is fetched (as a dependency). Notice in the image below that the marked folder & file were manually added by me (which makes the build work), but all other files (eg. under `/src`) were already there:
image

So I reckon something is potentially wrong with that symlink, or it could be that the `/include/buildfile` is never invoked? Again, I've barely used build2 so I'm just guessing here.

**Comment by helmesjo** [comment]
@Swat-SomeBug It's [this](https://github.com/helmesjo/convertible/tree/add_benchmark) repo but just as I was writing the steps on how to make it fail, it worked... I cloned my repo _fresh_, and by magic it just built straight away. I then tested the previous clone again and it still failed. After some extensive cleanup (remove config folders, wipe `.bdep` and re-init) did I get it to work again. Sorry for the detour, this had me scratching my head for many hours.

**Comment by helmesjo** [comment]
I guess this should be ready for completion? :)

**Pull request merged**
